### PR TITLE
Improve compiling in Docker container

### PR DESCRIPTION
**Pull request by StefanScherer**
Here is a simpler setup to compile and run the ippsample in a Docker container.

* Renamed `ippsample.docker` to `Dockerfile` to avoid `-f` option during build.
* Removed `MAINTAINER` instruction in Dockerfile as this keyword is deprecated.
* `COPY` the local sources into the Docker image to be able to compile local changes in the container.
* Added an entrypoint to start dbus and avahi-daemon
* Splitted the `./configure` and `make ; make install` into two RUN instruction to use Docker build cache
* Updated `DOCKER.md` to show how to directly run the ippsample binaries (eg. changing into the examples folder)

With the latest commit I also have added a `docker-compose.yml` which makes it easy to run the IPP server with the configuration given in the test folder and a specific hostname.

Run the IPP server (it will also build or update the Docker image):

```
$ docker-compose up ippserver
```

In another terminal run eg. the IPP find tool

```
$ docker-compose up ippfind
ippsample_ippserver_1 is up-to-date
Creating ippsample_ippfind_1 ... 
Creating ippsample_ippfind_1 ... done
Attaching to ippsample_ippfind_1
ippfind_1    |  * Starting system message bus dbus
ippfind_1    |    ...done.
ippfind_1    |  * Starting Avahi mDNS/DNS-SD Daemon avahi-daemon
ippfind_1    |    ...done.
ippfind_1    | ipp://ippserver.local:8991/ipp/print/ipp-everywhere-pdf
ippfind_1    | ipp://ippserver.local:8991/ipp/print/bar
ippfind_1    | ipp://ippserver.local:8991/ipp/print/foo
ippfind_1    | ipp://ippserver.local:8991/ipp/print/ipp-everywhere-raster
ippsample_ippfind_1 exited with code 0
```

Or run the IPP Everywhere test:

```
$ docker-compose up ipptest
```

### CODE REVIEW

**Comment by StefanScherer** [comment]
I have also added an example for the IPP Proxy in the `docker-compose.yml` to point back to the IPP server, just for an example:

```yaml
  ippproxy:
    build:
      context: .
      dockerfile: Dockerfile
    command: ippproxy -d ipp://ippserver.local:8991/ipp/print/foo ipp://ippserver.local:8991/ipp/print/bar
    depends_on:
      - "ippserver"
```

But when I run `docker-compose up ippproxy` it only shows 

```
$ docker-compose up ippproxy
ippsample_ippserver_1 is up-to-date
Creating ippsample_ippproxy_1 ... 
Creating ippsample_ippproxy_1 ... done
Attaching to ippsample_ippproxy_1
ippproxy_1   |  * Starting system message bus dbus
ippproxy_1   |    ...done.
ippproxy_1   |  * Starting Avahi mDNS/DNS-SD Daemon avahi-daemon
ippproxy_1   |    ...done.
ippproxy_1   | ippproxy: UUID for 'ipp://ippserver.local:8991/ipp/print/foo' is 'urn:uuid:01000000-597f-3000-541e-6051597f000'.
ippproxy_1   | ippproxy: Infrastructure printer at 'ipp://ippserver.local:8991/ipp/print/bar' is not responding, retrying in 30 seconds...
ippproxy_1   | ippproxy: Infrastructure printer at 'ipp://ippserver.local:8991/ipp/print/bar' is not responding, retrying in 30 seconds...
ippproxy_1   | ippproxy: Infrastructure printer at 'ipp://ippserver.local:8991/ipp/print/bar' is not responding, retrying in 30 seconds...
```

What am I doing wrong? 😅

**Comment by michaelrsweet** [comment]
The proxy/infrastructure support is currently not completed, so it won't work out of the box. Working on it...

**Comment by StefanScherer** [comment]
I've updated the `Dockerfile` to install all required prerequisites listed in `BUILD.md`. Now the binaries are built with `HAVE_SSL` defined that I wasn't are using the original `ippsample.docker` file. That's why I found #68.

**Comment by michaelrsweet** [comment]
I also added the new dependencies listed in BUILD.md to the Dockerfile.

**Pull request merged**
