### PR TITLE
Generate AppImage on Travis CI, closes #56

### LINKED ISSUE #56: Add AppImage support (and Travis)
Reference: https://appimage.org/

You should add support for an ippsample (or maybe just "ipp") AppImage that provides a "universal" Linux binary that can be built automagically via GitHub and Travis.

In addition to the usual AppImage.yaml stuff, you'll probalby want a configure option and stuff in the makefiles to have a configurable prefix so that the AppImage commands can be "ipp.server", "ipp.tool", etc. rather than "ipp.ippserver", etc.

:-)

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile the ippsample tools on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).

For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

__Please note:__ Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the Releases page of your project. This is what I recommend. See https://docs.travis-ci.com/user/deployment/releases/. If you want to do this for continuous builds, also see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

Closes https://github.com/istopwg/ippsample/issues/56

### CODE REVIEW

**Comment by probonopd** [comment]
You can see the build log for this at https://travis-ci.org/probonopd/ippsample/builds/295273697

Specifically, a download URL is given toward the end at https://travis-ci.org/probonopd/ippsample/builds/295273697#L1074

Using this, you can do the following:

```
wget "https://transfer.sh/kG2QQ/ippsample-git.75ecdb4-x86_64.AppImage"
chmod +x ippsample-git.75ecdb4-x86_64.AppImage 
ln -s ippsample-*-x86_64.AppImage ippfind
ln -s ippsample-*-x86_64.AppImage ippproxy
ln -s ippsample-*-x86_64.AppImage ippserver
ln -s ippsample-*-x86_64.AppImage ipptool

 ./ipptool -tv ipp://NPI5F036D.local:631/ipp/print get-printer-attributes.test
```

**Comment by michaelrsweet** [comment]
Considering

**Comment by probonopd** [comment]
Stuck on the naming on the binaries.

Even with `--with-name-prefix=ipp` https://travis-ci.org/probonopd/ippsample/builds/296984810#L422 it names the binaries wrongly: `PPproxy PPfind PPtool` https://travis-ci.org/probonopd/ippsample/builds/296984810#L645-L649

**Comment by KurtPfeifle** [comment]
I tried to build on a local Mac. The `--with-name-prefix=...` seems to be b0rken here, too. But funnily in a different way:

- The default build results are indeed named `ipp...`.
- But after `./configure --with-name-prefix=PP` the outcome is STILL `ipp...`

**Comment by michaelrsweet** [comment]
@KurtPfeifle @probonopd The binaries in the build directory will still be named ippfind, ippserver, ipptool, etc. - the renaming doesn't happen until installation.

That said, it looks like the tools makefile didn't put parens around the $IPP, causing the PP nonsense in the installed tools. And I forgot to rename the man pages. Fixed in:

[master d24cf0c] Fix renaming of files on install.

**Comment by probonopd** [comment]
Works as intended now:
https://transfer.sh/10o3Dj/ippsample-git.97c1bbf-x86_64.AppImage

**Comment by michaelrsweet** [comment]
OK, so Travis CI is no longer available for open source usage, will reconsider for Github CI, and we already have snap builds working.

**Pull request closed without merging**
