### PR TITLE
Issue 36 part 2

### PR DESCRIPTION
**Pull request by wifiprintguy**
Hopefully completes the case insensitive comparison of hostnames when using an EXPECT with WITH-ALL-HOSTNAMES

### CODE REVIEW

**Comment by michaelrsweet** [comment]
The whitespace changes make it really hard to see what was actually changed... :/

Trying a local diff...

**Comment by michaelrsweet** [comment]
OK, so with a local diff tool I can see the scope of the changes...

Aside from from reporting changes (to show the URI components in the EXPECTED report), this change uses strcasecmp (not _cups_strcasecmp) to compare the entire URI, however only the scheme and host are actually case-insensitive according to RFC 7230 which registers the "http" and "https" URI schemes. Section 2.7.3 says the following:

> The scheme and host are case-insensitive and normally provided in lowercase; all other components are compared in a case-sensitive manner.

I'll look into why the compare_uris function is not performing its function correctly and come up with an alternate fix.

**Comment by michaelrsweet** [comment]
Also, doing a strcasecmp of the whole string doesn't work for comparing just the scheme, host, resource, etc. components.

**Comment by michaelrsweet** [comment]
OK, I've pushed a fix for Issue #36, please test and let me know if there are still issues...

**Comment by wifiprintguy** [comment]
The compare_uris() function was called using get_string(), which was providing it with the hostname string fragments for a and b because it was picking those bits out based on the flags. The compare_uris() function was failing on line 780 with this:

    if (httpSeparateURI(HTTP_URI_CODING_ALL, a, ascheme, sizeof(ascheme), auserpass, sizeof(auserpass), ahost, sizeof(ahost), &aport, aresource, sizeof(aresource)) < HTTP_URI_STATUS_OK)
        return (-1);


I don't care who does the coding - I just wanted it to be fixed. 😊

**Pull request closed without merging**
