### PR TITLE
Merge ippdoclint code into the upstream repo (Issue #29)

### PR DESCRIPTION
**Pull request by rithvikp1998**
The pull request contains the code for the ippdoclint program written as part of Google Summer of Code 2018 [project.](https://summerofcode.withgoogle.com/projects/#6686515787202560) A comprehensive code review is still needed.

### CODE REVIEW

**Comment by rithvikp1998** [comment]
I am working to fix the failing CI check.

**Comment by michaelrsweet** [comment]
The reason this is failing is because the libraries used are not available on macOS and MUST NOT be hardcoded. I'll work on refactoring as needed...

**Comment by rithvikp1998** [comment]
@michaelrsweet I fixed the build issues by adding conditional compilation, can you please review the code and see if everything's ok?

**Comment by michaelrsweet** [comment]
@rithvikp1998 Will get to this as I can...

**Comment by michaelrsweet** [comment]
OK, I'll be tracking the merge progress in Issue #29; we won't be using the code exactly as-is and I need to update things for changes in ippserver/ippeveprinter as well.

**Pull request closed without merging**
