### PR TITLE
Fix clang error with dirabs[256]

### PR DESCRIPTION
**Pull request by ron42**
Use dirabs[PATH_MAX + 1]

### CODE REVIEW

**Comment by ron42** [comment]
See Issue #205

**Comment by michaelrsweet** [comment]
@ron42 It would be useful to know what the clang error actually is, since I am unable to reproduce this...

**Comment by ron42** [comment]
@michaelrsweet See issue #205

**Comment by michaelrsweet** [comment]
Fixed directly in issue #205.

**Pull request closed without merging**
