### PR TITLE
Fix pdftoppm invocation for Poppler pdftoppm

### PR DESCRIPTION
**Pull request by attah**
pdftoppm treats any second non-flag parameter as a PPM-file-prefix, creating files starting with "-", like "--1.pgm" instead of outputting to stdout. Omitting the prefix however, outputs to stdout.
Checked on pdftoppm 0.86.1 and 21.08.0.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Ok so Poppler pdftoppm is different from the original (upstream) Xpdf pdftoppm?

**Comment by michaelrsweet** [comment]
To make things clear - we need a solution that works for both Xpdf and Poppler, as Xpdf *requires* the “-“.

**Comment by attah** [comment]
Ah, i had not realized anyone was still using xpdf. That explains it (and makes this PR incorrect).
So, yes, they are different. Checked latest xpdf, and it does indeed not just support the "-", but require it.

**Comment by attah** [comment]
Having given it some more thought; checking for presence of Poppler/poppler (oppler?) in `pdftoppm -h` is still the only way that comes to mind.
But i'd need some ++ to my C to make a solution that i'd be good enough contributing.

**Comment by michaelrsweet** [comment]
Please file a bug against the poppler project on this - Xpdf has used this command syntax for a very long time.

I will look at adding a configure-time check for this, but such things are notoriously unstable.

**Comment by attah** [comment]
After doing some research, it seems Poppler and Xpdf have introduced the ability to output to stdout independently of, but likely inspired by, each other.
It seems Xpdf has had it from version 3.03 (2011), which is after the main Poppler forking point AFAIK.
Poppler introduced its version in 0.6.0 (2007).

But since Xpdf seems to not keep public repos it is of course not possible to know for sure who was first.
It is not in 3.02 (earlier in 2007) but also not in any of the subsequent published patches, so first published version is still in 2011 that i can see.

BTW, how are other CUPSy things not hit by this left right and center?
Most distros have switched (defaults and outright) from Xpdf years ago. (Redhat seemingly in '15, and Ububntu in '20)

Also; just to clarify, this is not something i mean to push to fulfill my own needs, i'm just trying to help give back to something i see as valuable.
If you still think it is valuable, i can definitely take the question to Poppler, but i wouldn't count on them being favorable towards it.

**Comment by attah** [comment]
Added a Poppler specific invocation behind an ifdef. 
TBD obviously if that is the correct name and way to do it, but the command line works well at least.
Since Poppler willl also need specific scaling options to get perfectly floored dimensions, i don't think there is a point to ask for allowing "-" as output prefix to mean stdout.

**Comment by attah** [comment]
I'm not sure i understand quite what crap you are referring to. Poppler is far from perfect, and the maintainer is indeed not much of a fan of the standalone tools it seems... But Poppler is much more actively maintained than XPDF (last release 9 months ago, and no public repo it seems). And from what i could find Linux distros switched over ages ago. I'm inclined to trust their judgement.

It's not that i'm asking that XPDF support is thrown out... just saying that it's going to be broken to most people. And for that matter i made my own tools long ago since i can accept GPL "infection"... I just think it's a shame to have the "standard" one be broken.

**Comment by michaelrsweet** [comment]
@attah What I mean is that Xpdf can be easily configured to only built non-desktop bits for use on a server. The same is not true of Poppler. Also, the Xpdf author provides more than just the official open source releases - it isn't a bleeding-edge public git repository but if you find a bug he will get you a fix pretty quickly and can provide licensing when the GPL becomes a problem.

Anyways, I *do* want to resolve this somehow because yes, many people do use Poppler and we should be compatible with both versions of pdftoppm. I'm just unwilling to remove Xpdf support because of it.

**Comment by attah** [comment]
Updated with possible solution. Consider it a draft still... and please do point out any issues you see with it.

**Comment by michaelrsweet** [comment]
I'm not crazy about looking at the "help" output...  Also, I'm not sure that forcing width/height to the media size is the correct behavior either (might result in asymmetric scaling, need to check...)

**Comment by attah** [comment]
Agreed... but compared to a define, i think it is preferable. And at least it is quite clear what it does.

Forcing dimensions will certainly produce interesting results if the input is not already the correct size.

But then again, anything that is not the correct size will _fail_ generally. This will "just" produce bad output instead of failing in some cases.
e.g. letter document with media set to a4, or for extra spice: https://wiki.debian.org/CUPSPdfToPdf?action=AttachFile&do=view&target=mixed.pdf (which neither succeeds on)

**Comment by michaelrsweet** [comment]
Using `-scale-to` for the long axis is probably the way to go, and the code needs to crop/expand the output as needed.

**Comment by michaelrsweet** [comment]
OK, I opted to use the "-v" (version) output, and also updated the code to use `-scale-to` for Poppler's pdftoppm and to crop/expand the bitmap we get as needed.

[master 2fc9274] Update ipptransform to support both Xpdf and Poppler pdftoppm (Issue #267)

**Pull request closed without merging**
